### ISSUE TITLE
Deleting the last menu item in a menu causes 'Index was outside the bounds of array'

### ISSUE THREAD

**Issue by tznind** [tznind/TerminalGuiDesigner#14]
Create a new MenuBar
Press F9 to edit the menu
Press Delete

```
Global Exception
Index was outside the bounds of the array.
   at Terminal.Gui.Menu.MoveUp()
   at Terminal.Gui.Menu.<>c__DisplayClass5_0.<.ctor>b__0()
   at Terminal.Gui.View.InvokeKeybindings(KeyEvent keyEvent)
   at Terminal.Gui.Menu.ProcessKey(KeyEvent kb)
   at Terminal.Gui.View.ProcessHotKey(KeyEvent keyEvent)
   at Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke)
   at Terminal.Gui.WindowsDriver.ProcessInput(InputRecord inputEvent)
   at Terminal.Gui.WindowsMainLoop.Terminal.Gui.IMainLoopDriver.MainIteratio
n()
   at Terminal.Gui.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
```

**Comment by tznind** [comment]
Fixed in 1.0.14
