### ISSUE TITLE
Null reference in RunState.Dispose()

### ISSUE THREAD

**Issue by tznind** [tznind/TerminalGuiDesigner#41]
Triggered in Linux closing app with Ctrl+Q at random

```
Global Exception
Object reference not set to an instance of an object.
   at Terminal.Gui.View.set_CanFocus(Boolean value)
   at Terminal.Gui.MenuBar.CleanUp()
   at Terminal.Gui.MenuBar.OnLeave(View view)
   at Terminal.Gui.View.SetHasFocus(Boolean value, View view, Boolean force)
   at Terminal.Gui.View.set_CanFocus(Boolean value)
   at Terminal.Gui.View.Remove(View view)
   at Terminal.Gui.View.Dispose(Boolean disposing)
   at Terminal.Gui.View.Dispose(Boolean disposing)
   at Terminal.Gui.TabView.Dispose(Boolean disposing)
   at Terminal.Gui.View.Dispose(Boolean disposing)
   at Terminal.Gui.View.Dispose(Boolean disposing)
   at Terminal.Gui.View.Dispose(Boolean disposing)
   at Terminal.Gui.Responder.Dispose()
   at Terminal.Gui.Application.RunState.Dispose(Boolean disposing)
   at Terminal.Gui.Application.RunState.Dispose()
   at Terminal.Gui.Application.End(RunState runState)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
```

**Comment by tig** [comment]
Likely fixed by 

- https://github.com/gui-cs/Terminal.Gui/pull/3339
